version: '3.8'

networks:
  hashservice:
    driver: bridge

services:
  service1:
    build:
      context: service1
    environment:
      - APP_CONFIG_PORT=50051
      - APP_CONFIG_DEBUG_LEVEL=5
    ports:
      - "50051:50051"
    networks:
      - hashservice
  service2:
    restart:
      always
    build:
      context: service2
    depends_on:
      postgresql:
        condition: service_started
    environment:
      - APP_CONFIG_POSTGRES_DB=service2_db
      - APP_CONFIG_POSTGRES_USER=service2
      - APP_CONFIG_POSTGRES_PASSWORD=service2
      - APP_CONFIG_POSTGRES_HOST=postgresql
      - APP_CONFIG_POSTGRES_PORT=5432
      - APP_CONFIG_PORT=8080
      - APP_CONFIG_DEBUG_LEVEL=5
      - APP_CONFIG_GRPC_HOST=service1
      - APP_CONFIG_GRPC_PORT=50051
    ports:
      - "8080:8080"
    networks:
      - hashservice
  postgresql:
    image: postgres:16
    container_name: service2-postgresql
    environment:
      - POSTGRES_DB=service2_db
      - POSTGRES_USER=service2
      - POSTGRES_PASSWORD=service2
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - hashservice
