version: '3.8'

services:
  pq-postgresql:
    image: postgres:16
    container_name: service2-postgresql
    environment:
      - POSTGRES_DB=service2_db
      - POSTGRES_USER=service2
      - POSTGRES_PASSWORD=service2
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "15432:5432"
