// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCheckHandlerFunc turns a function with the right signature into a get check handler
type GetCheckHandlerFunc func(GetCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCheckHandlerFunc) Handle(params GetCheckParams) middleware.Responder {
	return fn(params)
}

// GetCheckHandler interface for that can handle valid get check params
type GetCheckHandler interface {
	Handle(GetCheckParams) middleware.Responder
}

// NewGetCheck creates a new http.Handler for the get check operation
func NewGetCheck(ctx *middleware.Context, handler GetCheckHandler) *GetCheck {
	return &GetCheck{Context: ctx, Handler: handler}
}

/*
	GetCheck swagger:route GET /check getCheck

Получает по id хэш из хранилища (если есть)
*/
type GetCheck struct {
	Context *middleware.Context
	Handler GetCheckHandler
}

func (o *GetCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCheckParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
